In [1]:
import numpy as np

In [2]:
myarray=np.array([1,2,3,4,5],np.int64)

In [3]:
myarray

array([1, 2, 3, 4, 5], dtype=int64)

In [4]:
myarray[0]

1

In [5]:
array=np.array([[9,8,7,6]])

In [6]:
array[0,1]

8

In [7]:
myarray.shape

(5,)

In [8]:
myarray.dtype

dtype('int64')

**array creation methods**

In [9]:
#1)Conversion from other Python structures(like lists,tuples..)
list=np.array([1,2,3,4,5])
print(list)
l=np.array([[1,2,3],[5,6,7]])
print(l)
print(list.shape)
print(list.size)

[1 2 3 4 5]
[[1 2 3]
 [5 6 7]]
(5,)
5


In [10]:
#2)Intrinsic numpy array creation objects(eg:arange,ones,zeroes or etc..)
#i)USING ZEROS
zeros=np.zeros((2,5))#take this as rows and columns
print(zeros)
print(zeros.dtype)
print(zeros.shape)
#ii)USING ARANGE
r=np.arange(10)
print(r)#it will print an array upto the given range-1
print(r.dtype)
print(r.shape)
#iii)USING LINSPACE
lspace=np.linspace(1,5,12)
print(lspace)#it wil print equally spaced elemnts from 1 to 5 in 12 parts
#iv)USING EMPTY
emp=np.empty((4,6))
print(emp)#it will give random numbers in the form of 4 rows and 6 columns
emplike=np.empty_like(lspace)
print(emplike)#it will make the array empty
#v)USING IDENTITY
ide=np.identity(4)
print(ide)#it gives an 4x4 identity matrix
print(ide.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
(2, 5)
[0 1 2 3 4 5 6 7 8 9]
int32
(10,)
[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.39071275e-307
  1.89146896e-307 7.56571288e-307]
 [3.11525958e-307 1.24610723e-306 1.37962320e-306 1.29060871e-306
  2.22518251e-306 1.33511969e-306]
 [1.78022342e-306 1.05700345e-307 3.11525958e-307 1.69118108e-306
  8.06632139e-308 1.20160711e-306]
 [1.69119330e-306 1.29062229e-306 1.42417222e-306 1.33512648e-306
  7.56596412e-307 2.22522596e-306]]
[1.         1.36363636 1.72727273 2.09090909 2.45454545 2.81818182
 3.18181818 3.54545455 3.90909091 4.27272727 4.63636364 5.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


**RESHAPING AN ARRAY**

In [11]:
arr=np.arange(99)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [12]:
reshapedarray=arr.reshape(3,33)#it rehapes the given array into the 3 rows and 33 columns
print(reshapedarray)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [13]:
#converting the reshaped array into normal one
#USING RAVEL
normal=reshapedarray.ravel()
print(normal)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [14]:
normal.shape

(99,)

In [15]:
x=[[1,2,3],[4,5,6],[7,0,1]]
ar=np.array(x)
print(ar)

[[1 2 3]
 [4 5 6]
 [7 0 1]]


In [16]:
ar.sum(axis=0)#span the columns and gives the sum

array([12,  7, 10])

In [17]:
ar.sum(axis=1)#span the rows and gives the sum

array([ 6, 15,  8])

In [18]:
ar.T#TRANSPOSE THE ARRAY

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [19]:
ar.flat# by this we can make  an iterator

In [20]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
0
1


In [21]:
ar.ndim#gives dimensions


2

In [22]:
ar.size#gives size


9

In [23]:
ar.nbytes#how much bytes the array is taking 

36

**1-D ARRAY**

In [24]:
one=np.array([1,2,3,4,5])
print(one)

[1 2 3 4 5]


In [25]:
one.argmax()#gives the index of the largest element in the array

4

In [26]:
one.argmin()#gives the index of the smallest element in the array

0

In [27]:
one.argsort()#sorted array of indices

array([0, 1, 2, 3, 4], dtype=int64)

**2-D ARRAY**

In [28]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [29]:
ar.argmin()#this will straight all the elemnts firstgives the min one by counting from 0 

7

In [30]:
ar.argmax()#this will straight all the elements first giving max one by counting from 0

6

In [31]:
ar.argmax(axis=0)#from columns

array([2, 1, 1], dtype=int64)

In [32]:
ar.argmax(axis=1)#from rows

array([2, 2, 0], dtype=int64)

In [33]:
ar.argsort(axis=0)#gives the indices sorted at columns

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [34]:
ar.argsort(axis=1)#gives the indices sorted  at rows

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

**MATHEMATICAL OPERATIONS**

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [36]:
ar2=np.array([[1,4,5],[6,5,4],[9,8,7]])
print(ar2)

[[1 4 5]
 [6 5 4]
 [9 8 7]]


In [37]:
ar+ar2#sums up one by one serially

array([[ 2,  6,  8],
       [10, 10, 10],
       [16,  8,  8]])

In [38]:
ar*ar2#multiplies one by one serially

array([[ 1,  8, 15],
       [24, 25, 24],
       [63,  0,  7]])

In [39]:
np.sqrt(ar)#gives square root of element wise

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 0.        , 1.        ]])

In [40]:
ar.sum()


29

In [41]:
ar.max()

7

In [42]:
ar.min()

0

In [43]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [44]:
type(np.where(ar>5))

tuple

In [45]:
np.count_nonzero(ar)#gives the count of the non-zero elements

8

In [46]:
np.nonzero(ar)#gives the nonzero elements in the array

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

**CHECKING HOW NUMPY ARRAY TAKES LESS STORAGE THAN PYTHON ARRAY**

In [47]:
import sys

In [48]:
pythonarray=[1,2,3,4,5]

In [49]:
numpyarray=np.array([1,2,3,4,5])

In [50]:
sys.getsizeof(1)*len(pythonarray)

140

In [51]:
numpyarray.itemsize*numpyarray.size

20

**CONVERTING NUMPY ARRAY TO PYTHON LIST**

In [52]:
numpyarray.tolist()

[1, 2, 3, 4, 5]